const Data = [
    {
        SLA_Level: "2",
        acid: "1",
        adept: "NULL",
        air: "0",
        alchemist: "NULL",
        antipaladin: "NULL",
        area: "",
        augmented: "",
        bard: "NULL",
        bloodline: "",
        bloodrager: "2",
        casting_time: "1 standard action",
        chaotic: "0",
        cleric: "NULL",
        cold: "0",
        components: "V, S, M (rhubarb leaf and an adder's stomach), F (a dart)",
        costly_components: "0",
        curse: "0",
        darkness: "0",
        death: "0",
        deity: "",
        description: "An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.",
        description_formatted: "<p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p>",
        descriptor: "acid",
        disease: "0",
        dismissible: "0",
        divine_focus: "0",
        domain: "",
        draconic: "0",
        druid: "NULL",
        duration: "1 round + 1 round per three levels",
        earth: "0",
        effect: "one arrow of acid",
        electricity: "0",
        emotion: "0",
        evil: "0",
        fear: "0",
        fire: "0",
        focus: "1",
        force: "0",
        full_text: "<link rel=\"stylesheet\"href=\"PF.css\"><div class=\"heading\"><p class=\"alignleft\">Acid Arrow </p><div style=\"clear: both;\"></div></div><div><h5><b>School </b>conjuration (creation) [acid]; <b>Level </b>sorcerer/wizard 2, magus 2, bloodrager 2</h5><h5><b>Casting Time </b>1 standard action</h5><h5><b>Components </b>V, S, M (rhubarb leaf and an adder's stomach), F (a dart)</h5><h5><b>Range </b>long (400 ft. + 40 ft./level)</h5><h5><b>Effect </b>one arrow of acid</h5><h5><b>Duration </b>1 round + 1 round per three levels</h5><h5><b>Saving Throw </b>none; <b>Spell Resistance </b>no</h5></div><div><h4><p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p></h4></div>",
        good: "0",
        haunt_statistics: "",
        hunter: "NULL",
        id: "1",
        inquisitor: "NULL",
        investigator: "NULL",
        language_dependent: "0",
        lawful: "0",
        light: "0",
        linktext: "Acid Arrow",
        magus: "2",
        material: "1",
        material_costs: "NULL",
        meditative: "0",
        medium: "NULL",
        mesmerist: "NULL",
        mind_affecting: "0",
        mythic: "0",
        mythic_text: "",
        name: "Acid Arrow",
        occultist: "NULL",
        oracle: "NULL",
        pain: "0",
        paladin: "NULL",
        patron: "",
        poison: "0",
        psychic: "NULL",
        range: "long (400 ft. + 40 ft./level)",
        ranger: "NULL",
        ruse: "0",
        saving_throw: "none",
        school: "conjuration",
        shadow: "0",
        shaman: "NULL",
        shapeable: "0",
        short_description: " Ranged touch attack; 2d4 damage for 1 round + 1 round/three levels.",
        skald: "NULL",
        somatic: "1",
        sonic: "0",
        sor: "2",
        source: "PFRPG Core",
        spell_level: "sorcerer/wizard 2, magus 2, bloodrager 2",
        spell_resistance: "no",
        spiritualist: "NULL",
        subschool: "creation",
        summoner: "NULL",
        summoner_unchained: "NULL",
        targets: "",
        verbal: "1",
        water: "0",
        witch: "NULL",
        wiz: "2",
      },
      {
        SLA_Level: "2",
        acid: "1",
        adept: "NULL",
        air: "0",
        alchemist: "NULL",
        antipaladin: "NULL",
        area: "",
        augmented: "",
        bard: "NULL",
        bloodline: "",
        bloodrager: "2",
        casting_time: "1 standard action",
        chaotic: "0",
        cleric: "NULL",
        cold: "0",
        components: "V, S, M (rhubarb leaf and an adder's stomach), F (a dart)",
        costly_components: "0",
        curse: "0",
        darkness: "0",
        death: "0",
        deity: "",
        description: "An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.",
        description_formatted: "<p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p>",
        descriptor: "acid",
        disease: "0",
        dismissible: "0",
        divine_focus: "0",
        domain: "",
        draconic: "0",
        druid: "NULL",
        duration: "1 round + 1 round per three levels",
        earth: "0",
        effect: "one arrow of acid",
        electricity: "0",
        emotion: "0",
        evil: "0",
        fear: "0",
        fire: "0",
        focus: "1",
        force: "0",
        full_text: "<link rel=\"stylesheet\"href=\"PF.css\"><div class=\"heading\"><p class=\"alignleft\">Acid Arrow </p><div style=\"clear: both;\"></div></div><div><h5><b>School </b>conjuration (creation) [acid]; <b>Level </b>sorcerer/wizard 2, magus 2, bloodrager 2</h5><h5><b>Casting Time </b>1 standard action</h5><h5><b>Components </b>V, S, M (rhubarb leaf and an adder's stomach), F (a dart)</h5><h5><b>Range </b>long (400 ft. + 40 ft./level)</h5><h5><b>Effect </b>one arrow of acid</h5><h5><b>Duration </b>1 round + 1 round per three levels</h5><h5><b>Saving Throw </b>none; <b>Spell Resistance </b>no</h5></div><div><h4><p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p></h4></div>",
        good: "0",
        haunt_statistics: "",
        hunter: "NULL",
        id: "1",
        inquisitor: "NULL",
        investigator: "NULL",
        language_dependent: "0",
        lawful: "0",
        light: "0",
        linktext: "Acid Arrow",
        magus: "2",
        material: "1",
        material_costs: "NULL",
        meditative: "0",
        medium: "NULL",
        mesmerist: "NULL",
        mind_affecting: "0",
        mythic: "0",
        mythic_text: "",
        name: "Acid Arrow",
        occultist: "NULL",
        oracle: "NULL",
        pain: "0",
        paladin: "NULL",
        patron: "",
        poison: "0",
        psychic: "NULL",
        range: "long (400 ft. + 40 ft./level)",
        ranger: "NULL",
        ruse: "0",
        saving_throw: "none",
        school: "conjuration",
        shadow: "0",
        shaman: "NULL",
        shapeable: "0",
        short_description: " Ranged touch attack; 2d4 damage for 1 round + 1 round/three levels.",
        skald: "NULL",
        somatic: "1",
        sonic: "0",
        sor: "2",
        source: "PFRPG Core",
        spell_level: "sorcerer/wizard 2, magus 2, bloodrager 2",
        spell_resistance: "no",
        spiritualist: "NULL",
        subschool: "creation",
        summoner: "NULL",
        summoner_unchained: "NULL",
        targets: "",
        verbal: "1",
        water: "0",
        witch: "NULL",
        wiz: "2",
      },
      {
        SLA_Level: "2",
        acid: "1",
        adept: "NULL",
        air: "0",
        alchemist: "NULL",
        antipaladin: "NULL",
        area: "",
        augmented: "",
        bard: "NULL",
        bloodline: "",
        bloodrager: "2",
        casting_time: "1 standard action",
        chaotic: "0",
        cleric: "NULL",
        cold: "0",
        components: "V, S, M (rhubarb leaf and an adder's stomach), F (a dart)",
        costly_components: "0",
        curse: "0",
        darkness: "0",
        death: "0",
        deity: "",
        description: "An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.",
        description_formatted: "<p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p>",
        descriptor: "acid",
        disease: "0",
        dismissible: "0",
        divine_focus: "0",
        domain: "",
        draconic: "0",
        druid: "NULL",
        duration: "1 round + 1 round per three levels",
        earth: "0",
        effect: "one arrow of acid",
        electricity: "0",
        emotion: "0",
        evil: "0",
        fear: "0",
        fire: "0",
        focus: "1",
        force: "0",
        full_text: "<link rel=\"stylesheet\"href=\"PF.css\"><div class=\"heading\"><p class=\"alignleft\">Acid Arrow </p><div style=\"clear: both;\"></div></div><div><h5><b>School </b>conjuration (creation) [acid]; <b>Level </b>sorcerer/wizard 2, magus 2, bloodrager 2</h5><h5><b>Casting Time </b>1 standard action</h5><h5><b>Components </b>V, S, M (rhubarb leaf and an adder's stomach), F (a dart)</h5><h5><b>Range </b>long (400 ft. + 40 ft./level)</h5><h5><b>Effect </b>one arrow of acid</h5><h5><b>Duration </b>1 round + 1 round per three levels</h5><h5><b>Saving Throw </b>none; <b>Spell Resistance </b>no</h5></div><div><h4><p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p></h4></div>",
        good: "0",
        haunt_statistics: "",
        hunter: "NULL",
        id: "1",
        inquisitor: "NULL",
        investigator: "NULL",
        language_dependent: "0",
        lawful: "0",
        light: "0",
        linktext: "Acid Arrow",
        magus: "2",
        material: "1",
        material_costs: "NULL",
        meditative: "0",
        medium: "NULL",
        mesmerist: "NULL",
        mind_affecting: "0",
        mythic: "0",
        mythic_text: "",
        name: "Acid Arrow",
        occultist: "NULL",
        oracle: "NULL",
        pain: "0",
        paladin: "NULL",
        patron: "",
        poison: "0",
        psychic: "NULL",
        range: "long (400 ft. + 40 ft./level)",
        ranger: "NULL",
        ruse: "0",
        saving_throw: "none",
        school: "conjuration",
        shadow: "0",
        shaman: "NULL",
        shapeable: "0",
        short_description: " Ranged touch attack; 2d4 damage for 1 round + 1 round/three levels.",
        skald: "NULL",
        somatic: "1",
        sonic: "0",
        sor: "2",
        source: "PFRPG Core",
        spell_level: "sorcerer/wizard 2, magus 2, bloodrager 2",
        spell_resistance: "no",
        spiritualist: "NULL",
        subschool: "creation",
        summoner: "NULL",
        summoner_unchained: "NULL",
        targets: "",
        verbal: "1",
        water: "0",
        witch: "NULL",
        wiz: "2",
      },
      {
        SLA_Level: "2",
        acid: "1",
        adept: "NULL",
        air: "0",
        alchemist: "NULL",
        antipaladin: "NULL",
        area: "",
        augmented: "",
        bard: "NULL",
        bloodline: "",
        bloodrager: "2",
        casting_time: "1 standard action",
        chaotic: "0",
        cleric: "NULL",
        cold: "0",
        components: "V, S, M (rhubarb leaf and an adder's stomach), F (a dart)",
        costly_components: "0",
        curse: "0",
        darkness: "0",
        death: "0",
        deity: "",
        description: "An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.",
        description_formatted: "<p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p>",
        descriptor: "acid",
        disease: "0",
        dismissible: "0",
        divine_focus: "0",
        domain: "",
        draconic: "0",
        druid: "NULL",
        duration: "1 round + 1 round per three levels",
        earth: "0",
        effect: "one arrow of acid",
        electricity: "0",
        emotion: "0",
        evil: "0",
        fear: "0",
        fire: "0",
        focus: "1",
        force: "0",
        full_text: "<link rel=\"stylesheet\"href=\"PF.css\"><div class=\"heading\"><p class=\"alignleft\">Acid Arrow </p><div style=\"clear: both;\"></div></div><div><h5><b>School </b>conjuration (creation) [acid]; <b>Level </b>sorcerer/wizard 2, magus 2, bloodrager 2</h5><h5><b>Casting Time </b>1 standard action</h5><h5><b>Components </b>V, S, M (rhubarb leaf and an adder's stomach), F (a dart)</h5><h5><b>Range </b>long (400 ft. + 40 ft./level)</h5><h5><b>Effect </b>one arrow of acid</h5><h5><b>Duration </b>1 round + 1 round per three levels</h5><h5><b>Saving Throw </b>none; <b>Spell Resistance </b>no</h5></div><div><h4><p>An arrow of acid springs from your hand and speeds to its target. You must succeed on a ranged touch attack to hit your target. The arrow deals 2d4 points of acid damage with no splash damage. For every three caster levels you possess, the acid, unless neutralized, lasts for another round (to a maximum of 6 additional rounds at 18th level), dealing another 2d4 points of damage in each round.</p></h4></div>",
        good: "0",
        haunt_statistics: "",
        hunter: "NULL",
        id: "1",
        inquisitor: "NULL",
        investigator: "NULL",
        language_dependent: "0",
        lawful: "0",
        light: "0",
        linktext: "Acid Arrow",
        magus: "2",
        material: "1",
        material_costs: "NULL",
        meditative: "0",
        medium: "NULL",
        mesmerist: "NULL",
        mind_affecting: "0",
        mythic: "0",
        mythic_text: "",
        name: "Acid Arrow",
        occultist: "NULL",
        oracle: "NULL",
        pain: "0",
        paladin: "NULL",
        patron: "",
        poison: "0",
        psychic: "NULL",
        range: "long (400 ft. + 40 ft./level)",
        ranger: "NULL",
        ruse: "0",
        saving_throw: "none",
        school: "conjuration",
        shadow: "0",
        shaman: "NULL",
        shapeable: "0",
        short_description: " Ranged touch attack; 2d4 damage for 1 round + 1 round/three levels.",
        skald: "NULL",
        somatic: "1",
        sonic: "0",
        sor: "2",
        source: "PFRPG Core",
        spell_level: "sorcerer/wizard 2, magus 2, bloodrager 2",
        spell_resistance: "no",
        spiritualist: "NULL",
        subschool: "creation",
        summoner: "NULL",
        summoner_unchained: "NULL",
        targets: "",
        verbal: "1",
        water: "0",
        witch: "NULL",
        wiz: "2",
      }
]

export default Data